### ISSUE TITLE
logged out users aren't redirected from dashboard

### ISSUE THREAD

**Issue by jonyonson** [Lambda-School-Labs/ema-therapy-fe#30]
If you are logged out of the app (or get logged out if the auth token expires), you can still visit any of the routes (except for `/profile`) and it will throw a `TypeError`.

We need to either make all routes a `PrivateRoute` or render them conditionally based on `isAuthenticated`.

**Comment by allisonkydy** [comment]
PrivateRoute already set up, made the public routes private
