### ISSUE TITLE
mood preview card doesn't truncate text

### ISSUE THREAD

**Issue by allisonkydy** [Lambda-School-Labs/ema-therapy-fe#32]
all of the text from a mood entry is displayed in the preview, which can blow up the height.

**Comment by jonyonson** [comment]
I think we definitely need to truncate the text in case there is a long one, but also if you change the Dashboard's styling and give `dashboard-main` a bottom padding of 80px (height of nav bar plus a little) and take away the `height: 100%` it should fix the issue where the last card gets partially cut off.

```
const StyledDashboard = styled.div`
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: space-between;

  .dashboard-main {
    padding: 0 30px 80px;
  }
`;
```
